### PR TITLE
Added some test attributes

### PR DESCRIPTION
**Pull request by danielcirket**
Unashamedly taken from a previous project

### CODE REVIEW

**Comment by smudge202** [comment]
Looks like code I wrote at some stage. :D

I wanted to use @herecydev's [nuget package](https://www.nuget.org/packages/testattributes) but it's a little behind due to xunit changes and foo. Would still rather wait for the official package than steal it. :D

**Comment by ghost** [comment]
Cmon @herecydev. WTB: New update

**Comment by danielcirket** [comment]
That's no problem :D

**Comment by herecydev** [comment]
Check 2.0.0-rc1 and report any problems. Not promising anything. Need some help with it, not totally convinced it's playing ball.

**Comment by danielcirket** [comment]
@herecydev, I'll check it out tomorrow and report back / help fix anything I come across

**Comment by smudge202** [comment]
Replaced by #13

**Pull request closed without merging**
