### PR TITLE
Changed unit to component, removed xunit as a dependency.

### PR DESCRIPTION
**Pull request by herecydev**
Right, categories are running through the command line. Test explorer has nothing, which I've raised before.

### CODE REVIEW

**Comment by smudge202** [comment]
What are we defining as `Unit` vs `Component`?

Also, did you get latest; looks like you only updated one of the test projects? (There's two).

Yeh, I remember you saying something about the categories and test explorer being junk. No probs if we can still categories through the runner (and therefore through the `test` command in `project.json` I assume?)

**Comment by herecydev** [comment]
I Forked and committed to dev, so fairly sure that's the latest. I saw a `ComponentTests` file so I thought these were component tests?

**Comment by danielcirket** [comment]
Was going to ask the same question - damn you @smudge202 beat me to it!

**Comment by danielcirket** [comment]
I feel like these tests should still be [Unit] though, @herecydev let me know if I'm wrong!

**Comment by smudge202** [comment]
`Component` was shorthand for `Entity Component System` which is a bit of a mouthful. That's twice the name has bitten me in the ass; should I go for `EntityComponentSystem` instead then?

**Comment by danielcirket** [comment]
@smudge202 I think it would be better to rename, we know / should know that `Component` is the `Entity Component System` but would be clearer for others looking/contributing going forward.

**Comment by herecydev** [comment]
I would call a unit tests file: _nameoffiletotest_+tests

In this example you are using DI to resolve an instance of `ComponentSystem`. This would make these a component test at minimum. For unit tests you would target the class directly. Thoughts?

**Comment by smudge202** [comment]
All of our tests go through DI. As such, fair point, they're probably all Component tests. The implementations are `internal sealed` and we're not using `InteralsVisibleTo`; I like the idea of testing the interface as we right now, even if that does promote our tests to `Component`.

**Comment by danielcirket** [comment]
@smudge202 @herecydev  works for me :shipit: :D

**Comment by smudge202** [comment]
As per above comments, the tests in `EventStream.Tests` will also need to be promoted to `Component`.

I've raised #22 to cover the `Component` naming issue.

**Comment by ghost** [comment]
:shipit:

**Comment by herecydev** [comment]
:shipit:

**Comment by smudge202** [comment]
> **As per above comments, the tests in EventStream.Tests will also need to be promoted to Component.**

**Comment by smudge202** [comment]
#23 beat this PR to the line so is conflicted. I'll sort it tonight if someone doesn't beat me to it.

**Comment by danielcirket** [comment]
See PR #24

**Comment by smudge202** [comment]
Replaced by #24

**Pull request closed without merging**
